mtcars
df=mtcars
df
split=sample.split(df,SplitRatio=0.8)
training_set=subset(df,split==TRUE)
test_set=subset(df,split==FALSE)
training_set
fit=glm(factor(am)~mpg+cyl+disp+hp+drat+wt+qsec+vs+gear+carb,data=mtcars,family=binomial)
fit
summary(fit)
pred_am=predict(fit,type="response",newdata=test_set)
pred_am_2=ifelse(pred_am>0.5,1,0)
pred_am_2
cm=table(test_set$am,pred_am_2)
cm
library(rms)
fullmodel=fastbw(lrm(factor(am)~mpg+cyl+disp+hp+drat+wt+qsec+vs+gear+carb,data=mtcars,family=binomial),type="p")
step1=stepAIC(fit,direction="backward")
